
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#import "themes/default.typ" as internal: (
  glossarium_version,
  ATTRIBUTES,
  default-shorthands,
  default-capitalize,
  there-are-refs,
  is-first,
  has-short,
  has-long,
  has-artshort,
  has-artlong,
  has-plural,
  has-longplural,
  has-description,
  has-group,
  has-sort,
  has-styles,
  has-custom,
  get-attribute,
  is-upper,
  default-plural,
  refrule,
  default-print-back-references,
  default-print-description,
  default-group-break,
  default-print-gloss,
  default-print-glossary,
  default-print-group-heading,
  default-print-reference,
  default-print-title,
  default-group-break,
)

#import "themes/default.typ": (
  gls,
  agls,
  glspl,
  make-glossary,
  register-glossary,
  reset-counts,
  print-gloss,
  print-glossary,
  gls-key,
  gls-short,
  gls-artshort,
  gls-plural,
  gls-long,
  gls-artlong,
  gls-longplural,
  gls-description,
  gls-group,
  gls-custom,
  get-entry-back-references,
  count-refs,
  count-all-refs,
  there-are-refs,
  Gls,
  Glspl,
  style-entries,
  //
)
